"""MariaDB init

Revision ID: 8f6fac6e97e6
Revises: 
Create Date: 2025-06-18 11:54:57.264777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f6fac6e97e6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('mfa_secret', sa.String(length=32), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('context_scope',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('responsible', sa.String(length=100), nullable=True),
    sa.Column('coordinator', sa.String(length=100), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('last_update', sa.Date(), nullable=True),
    sa.Column('service_description', sa.Text(), nullable=True),
    sa.Column('knowledge', sa.Text(), nullable=True),
    sa.Column('interfaces', sa.Text(), nullable=True),
    sa.Column('mission_critical', sa.String(length=255), nullable=True),
    sa.Column('support_contracts', sa.String(length=255), nullable=True),
    sa.Column('security_supplier', sa.String(length=255), nullable=True),
    sa.Column('user_amount', sa.Integer(), nullable=True),
    sa.Column('scope_description', sa.Text(), nullable=True),
    sa.Column('risk_assessment_human', sa.Boolean(), nullable=True),
    sa.Column('risk_assessment_process', sa.Boolean(), nullable=True),
    sa.Column('risk_assessment_technological', sa.Boolean(), nullable=True),
    sa.Column('ai_model', sa.Boolean(), nullable=True),
    sa.Column('project_leader', sa.String(length=100), nullable=True),
    sa.Column('risk_owner', sa.String(length=100), nullable=True),
    sa.Column('product_owner', sa.String(length=100), nullable=True),
    sa.Column('technical_administrator', sa.String(length=100), nullable=True),
    sa.Column('security_manager', sa.String(length=100), nullable=True),
    sa.Column('incident_contact', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('component',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('info_type', sa.String(length=100), nullable=True),
    sa.Column('info_owner', sa.String(length=100), nullable=True),
    sa.Column('user_type', sa.String(length=100), nullable=True),
    sa.Column('process_dependencies', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('context_scope_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['context_scope_id'], ['context_scope.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('context_scope_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['context_scope_id'], ['context_scope.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('context_scope_id')
    )
    op.create_table('ai_identificatie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('No AI', 'Unacceptable risk', 'High risk', 'Limited risk', 'Minimal risk', name='ai_category'), nullable=True),
    sa.Column('motivatie', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['component.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('availability_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('mtd', sa.String(length=50), nullable=True),
    sa.Column('rto', sa.String(length=50), nullable=True),
    sa.Column('rpo', sa.String(length=50), nullable=True),
    sa.Column('masl', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['component.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consequences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('consequence_category', sa.String(length=255), nullable=True),
    sa.Column('security_property', sa.String(length=100), nullable=True),
    sa.Column('consequence_worstcase', sa.Text(), nullable=True),
    sa.Column('justification_worstcase', sa.Text(), nullable=True),
    sa.Column('consequence_realisticcase', sa.Text(), nullable=True),
    sa.Column('justification_realisticcase', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['component.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('consequences')
    op.drop_table('availability_requirements')
    op.drop_table('ai_identificatie')
    op.drop_table('summary')
    op.drop_table('component')
    op.drop_table('context_scope')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
