"""Add incident response tables

Revision ID: 20260211_0018
Revises: 20260211_0017
Create Date: 2026-02-11 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20260211_0018'
down_revision = '20260211_0017'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incident_scenarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['bia_components.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incident_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('actions_first_hour', sa.Text(), nullable=True),
    sa.Column('alternatives', sa.Text(), nullable=True),
    sa.Column('rto', sa.String(length=255), nullable=True),
    sa.Column('rpo', sa.String(length=255), nullable=True),
    sa.Column('contact_list', sa.Text(), nullable=True),
    sa.Column('manual_procedures', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['scenario_id'], ['incident_scenarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('incident_steps')
    op.drop_table('incident_scenarios')
    # ### end Alembic commands ###
