"""Add maturity tables

Revision ID: ec5ce35d1bd0
Revises: 20251205_0015
Create Date: 2026-02-09 07:53:03.919825

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ec5ce35d1bd0'
down_revision = '20251205_0015'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maturity_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('control_id', sa.Integer(), nullable=False),
    sa.Column('assessor_id', sa.Integer(), nullable=False),
    sa.Column('current_level', sa.Enum('INITIAL', 'MANAGED', 'DEFINED', 'QUANTITATIVELY_MANAGED', 'OPTIMIZING', name='maturitylevel'), nullable=False),
    sa.Column('target_level', sa.Enum('INITIAL', 'MANAGED', 'DEFINED', 'QUANTITATIVELY_MANAGED', 'OPTIMIZING', name='maturitylevel'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['control_id'], ['csa_controls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('maturity_assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_maturity_assessments_assessor_id'), ['assessor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_maturity_assessments_control_id'), ['control_id'], unique=False)

    op.create_table('maturity_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Enum('INITIAL', 'MANAGED', 'DEFINED', 'QUANTITATIVELY_MANAGED', 'OPTIMIZING', name='maturitylevel'), nullable=False),
    sa.Column('requirement_key', sa.String(length=50), nullable=False),
    sa.Column('compliant', sa.Boolean(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['maturity_assessments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('maturity_answers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_maturity_answers_assessment_id'), ['assessment_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maturity_answers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_maturity_answers_assessment_id'))

    op.drop_table('maturity_answers')
    with op.batch_alter_table('maturity_assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_maturity_assessments_control_id'))
        batch_op.drop_index(batch_op.f('ix_maturity_assessments_assessor_id'))

    op.drop_table('maturity_assessments')
    # ### end Alembic commands ###
